### PR TITLE
feat: improve general deploy experience

### PR DESCRIPTION
**Pull request by ThallesP**
Hey! Thanks for the great software, helped us a lot in our startup. 
Here's a list of things this PR will make it better to deploy:

- Remove the need for email provider when creating live keys
- Remove the need for psql and thus db-init (it'll run every time the server is started)
- Added support for S3 compatible providers
- Added `/api/health` endpoint that checks all server dependencies (useful for services like Railway or Render)

Also, hoping on adding an automatically build system using Github Actions for the Docker Image and an option to disable user sign ups.

And also, would you guys mind in me adding my Railway template as an option of deploy in the README (one-click deploy of Interval)? I'm asking this because I'll earn some kickback from that template and want to be transparent about it. If not, it's completely fine :)

### CODE REVIEW

**Review by jacobmischka — APPROVED** [review]
This looks great, thanks!

**Comment by jacobmischka** [comment]
> And also, would you guys mind in me adding my Railway template as an option of deploy in the README (one-click deploy of Interval)?

I'm fine with it if you point the template back to this repo before making the PR :)

**Comment by gabrielbryk** [comment]
@jacobmischka This is great but it didn't get pushed to the public npm repo, any chance that can happen?

**Comment by jacobmischka** [comment]
Oops sorry. Just published `1.1.0`, thanks

**Comment by gabrielbryk** [comment]
@alexarena Any change the public docker could receive this update?

**Comment by OliverGilan** [comment]
Will this be pushed to docker?

**Comment by muametgrooby** [comment]
one year later still not pushed in docker @alexarena @jacobmischka

**Pull request merged**
